//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgropuliApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public string Reference { get; set; }
        public System.DateTime Created { get; set; }
        public string Username { get; set; }
        public string Customer { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> PaymentDateTime { get; set; }
        public string PayuState { get; set; }
        public string PayuResponseCode { get; set; }
        public string PayuReference { get; set; }
        public string PayuTransaction { get; set; }
        public string PayuPaymentMethod { get; set; }
        public string PayuPaymentType { get; set; }
        public string TypeMod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
        public virtual User User { get; set; }
    }
}
