//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgropuliApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Favor = new HashSet<Favor>();
            this.Order = new HashSet<Order>();
            this.Referral = new HashSet<Referral>();
            this.WorkWithUs = new HashSet<WorkWithUs>();
        }
    
        public string Username { get; set; }
        public string Password { get; set; }
        public int RoleId { get; set; }
        public string NationalId { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Town { get; set; }
        public string Vereda { get; set; }
        public string Phone { get; set; }
        public string Farm { get; set; }
        public string Crop { get; set; }
        public string Location { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string CedulaRef { get; set; }
        public Nullable<int> TypeProveedorId { get; set; }
        public Nullable<int> TypeSubProveedorId { get; set; }
        public Nullable<int> DepartamentoId { get; set; }
        public Nullable<int> CiudadId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favor> Favor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Referral> Referral { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkWithUs> WorkWithUs { get; set; }
    }
}
